

pipeline {

  agent any

   environment {
        HTTP_PROXY = 'http://127.0.0.1:9888'
        JAVA_HOME = '/usr/lib/jvm/java-17-openjdk'
        PATH = "${JAVA_HOME}/bin:${PATH}"
   }

  stages {

    stage('Build Docker Image') {
    steps {
        script {
            echo "🏗️ Building Docker image from jenkins/Dockerfile"
            sh 'docker build -f jenkins/Dockerfile -t pr-build-image .'
        }
    }
}
    stage('Build') {
      environment {
        JAVA_HOME = '/usr/lib/jvm/java-11-openjdk'
        PATH = "${JAVA_HOME}/bin:${PATH}"
      }
      steps {
        sh './gradlew clean assemble'

      }
    }

    stage('Unit Tests') {
      environment {
        JAVA_HOME = '/usr/lib/jvm/java-11-openjdk'
        PATH = "${JAVA_HOME}/bin:${PATH}"
      }
      steps {
        sh './gradlew test'
      }
      post {
        always {
          junit 'build/test-results/test/*.xml'
        }
      }
    }

    stage('Database Tests') {
      environment {
        JAVA_HOME = '/usr/lib/jvm/java-11-openjdk'
        PATH = "${JAVA_HOME}/bin:${PATH}"
      }
      steps {
        sh './gradlew integrate'
      }
      post {
        always {
          junit 'build/test-results/integrate/*.xml'
        }
      }
    }

    stage('BDD Tests') {
      environment {
        JAVA_HOME = '/usr/lib/jvm/java-11-openjdk'
        PATH = "${JAVA_HOME}/bin:${PATH}"
      }
      steps {
        sh './gradlew generateCucumberReports'
        sh './gradlew jacocoTestReport'
      }
      post {
          always {
            junit 'build/test-results/bdd/*.xml'
          }
        }
    }

    stage('Static Analysis') {
        environment {
          JAVA_HOME = '/usr/lib/jvm/java-11-openjdk'
          PATH = "${JAVA_HOME}/bin:${PATH}"
        }      
      
      steps{
        sh './gradlew sonarqube -Dsonar.host.url=https://bug-free-train-977r5wwj74jj2pv6p-9000.app.github.dev/ -Dsonar.login="admin" -Dsonar.password="new_admin"'
      }
    }
  }
}
